/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LocalSlugRouteImport } from './routes/local.$slug'
import { Route as AdminPontosRouteImport } from './routes/admin.pontos'
import { Route as AdminPlanosRouteImport } from './routes/admin.planos'
import { Route as AdminEventosRouteImport } from './routes/admin.eventos'
import { Route as AdminEmpresasRouteImport } from './routes/admin.empresas'
import { Route as AdminConfigRouteImport } from './routes/admin.config'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'

const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LocalSlugRoute = LocalSlugRouteImport.update({
  id: '/local/$slug',
  path: '/local/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPontosRoute = AdminPontosRouteImport.update({
  id: '/pontos',
  path: '/pontos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventosRoute = AdminEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresasRoute = AdminEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/empresas': typeof EmpresasRoute
  '/explorar': typeof ExplorarRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/pontos': typeof AdminPontosRoute
  '/local/$slug': typeof LocalSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/empresas': typeof EmpresasRoute
  '/explorar': typeof ExplorarRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/pontos': typeof AdminPontosRoute
  '/local/$slug': typeof LocalSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/empresas': typeof EmpresasRoute
  '/explorar': typeof ExplorarRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/pontos': typeof AdminPontosRoute
  '/local/$slug': typeof LocalSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/empresas'
    | '/explorar'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/config'
    | '/admin/empresas'
    | '/admin/eventos'
    | '/admin/planos'
    | '/admin/pontos'
    | '/local/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/empresas'
    | '/explorar'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/config'
    | '/admin/empresas'
    | '/admin/eventos'
    | '/admin/planos'
    | '/admin/pontos'
    | '/local/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/empresas'
    | '/explorar'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/config'
    | '/admin/empresas'
    | '/admin/eventos'
    | '/admin/planos'
    | '/admin/pontos'
    | '/local/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  EmpresasRoute: typeof EmpresasRoute
  ExplorarRoute: typeof ExplorarRoute
  LocalSlugRoute: typeof LocalSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/local/$slug': {
      id: '/local/$slug'
      path: '/local/$slug'
      fullPath: '/local/$slug'
      preLoaderRoute: typeof LocalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pontos': {
      id: '/admin/pontos'
      path: '/pontos'
      fullPath: '/admin/pontos'
      preLoaderRoute: typeof AdminPontosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eventos': {
      id: '/admin/eventos'
      path: '/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AdminEventosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/empresas': {
      id: '/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AdminEmpresasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminEmpresasRoute: typeof AdminEmpresasRoute
  AdminEventosRoute: typeof AdminEventosRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminPontosRoute: typeof AdminPontosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminEmpresasRoute: AdminEmpresasRoute,
  AdminEventosRoute: AdminEventosRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminPontosRoute: AdminPontosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  EmpresasRoute: EmpresasRoute,
  ExplorarRoute: ExplorarRoute,
  LocalSlugRoute: LocalSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
